language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false
dist: xenial

addons:
  apt:
      packages:
          - shellcheck

script:
  - shellcheck *.sh

matrix:
  fast_finish: true
